Refactor, Add tests, Add test coverage
siftrics/sight-clojure pull request #3
Opened 2020-03-05 05:14 UTC by ashwinbhaskar

The failure threshold is set to 85%

2020-03-05 05:15 UTC, ashwinbhaskar commented
@siftrics Have added tests. Covers 85.75% of the code. Also did some refactoring. Can you once check if it works and update it here?

2020-03-09 12:26 UTC, siftrics commented
@ashwinbhaskar Gonna get to this today!

2020-03-18 04:33 UTC, ashwinbhaskar commented
@siftrics the response now looks like this (using clojure keywords)

```
{
      :pages : [
        {
          :error: "",
          :file-index: 0,
          :page-number: 1,
          :number-of-pages-in-file: 3,
          :recognized-text: [
                                          {:top-left-y 301,
                             :bottom-right-y 340,
                             :bottom-left-x 1318,
                             :top-right-x 1616,
                             :bottom-left-y 340,
                             :top-right-y 301,
                             :top-left-x 1318,
                             :bottom-right-x 1616,
                             :confidence 0.11501831809890184,
                             :text "foos"}]
        },
        
      ]
}
```

So, you might have to bump up the version of the  client.

2020-03-24 15:46 UTC, siftrics requested changes
@ashwinbhaskar Finally got a chance to review this. All the code changes look great.

Before merging, in addition to bumping the version to 1.1.0 in project.clj, can you please make these changes:

- **README.md**
  - Lines 12, 18, 24, and 33: Bump version to 1.1.0.
  - Lines 51 and 98: Make sure the usage example reflects the changes from this PR. You can update the example, if necessary.
  - Lines 56-78 and 76-90: Either change these examples to use the new keywords (`:recognized-text`, etc.), or write a short sentence stating how to access the fields now.
  - Line 111: You can mention you are the lead maintainer of this repository, if you want.

(I couldn't make inline comments because README.md wasn't modified near these lines)

2020-03-24 15:46 UTC, siftrics commented on project.clj
>    :description "Official Clojure client for the Sight API, a text recognition service"
Let's bump the version to 1.1.0.

2020-03-25 01:52 UTC, ashwinbhaskar commented on project.clj
>    :description "Official Clojure client for the Sight API, a text recognition service"
done

2020-03-25 01:53 UTC, ashwinbhaskar commented
@siftrics update version, usage and maintainer info in readme

2020-03-25 15:53 UTC, siftrics approved these changes

2020-03-25 15:53 UTC, merged